name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - typing
  - fonts-wqy-zenhei  # 文泉驿正黑
  - fonts-wqy-microhei # 文泉驿微米黑
  - noto-fonts-sc      # Google Noto Sans CJK SC
  - pip
  - pip:
    - Ipython
    - jupyter
    - ipykernel
    - ipywidgets
    - jupyterlab
