name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - typing
  - platform
  - pip
  - pip:
    - Ipython
    - jupyter
    - ipykernel
    - ipywidgets
    - jupyterlab
